//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAB_Merchant_Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointingAccountReference
    {
        public int Id { get; set; }
        public string Reference { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> LogId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual UserLog UserLog { get; set; }
    }
}
