//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAB_Merchant_Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public int Id { get; set; }
        public string Identifier { get; set; }
        public string SourceID { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransactionType { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string CoreBankingReference { get; set; }
        public string ThirdPartyReference { get; set; }
        public int LogId { get; set; }
        public string ResponseJson { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedDate { get; set; }
    
        public virtual UserLog UserLog { get; set; }
    }
}
