//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAB_Merchant_Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserLog()
        {
            this.TransactionLogs = new HashSet<TransactionLog>();
        }
    
        public int Id { get; set; }
        public string UserAgent { get; set; }
        public string UserFunction { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string TransStatus { get; set; }
        public string SourceID { get; set; }
        public string SourceName { get; set; }
        public string RequestBody { get; set; }
        public string ResponseBody { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLog> TransactionLogs { get; set; }
    }
}
